BOARDINC += $(BOARD_DIR)/generated/controllers/generated

BOARDCPPSRC =  $(BOARD_DIR)/board_configuration.cpp \
    $(BOARD_DIR)/default_tune.cpp \


IS_STM32F429 = yes
# defines SHORT_BOARD_NAME
include $(BOARD_DIR)/meta-info.env

# one day when we are grown ups and can coordinate a real life test we shall revisit https://github.com/rusefi/rusefi/issues/6008
DDEFS += -DDISABLE_PIN_STATE_VALIDATION=TRUE

# reduce memory usage monitoring
DDEFS += -DRAM_UNUSED_SIZE=100

# assign critical LED to a non-existent pin
DDEFS += -DLED_CRITICAL_ERROR_BRAIN_PIN=Gpio::I15

# MAJOR HACK? SOMETHING IS FUNNY HERE?!
DDEFS += -DDISABLE_PIN_STATE_VALIDATION=TRUE

# temporary or not? (pps noise stuff)
DDEFS += -DETB_INTERMITTENT_LIMIT=60001

DDEFS += -DSTM32_ADC_USE_ADC3=TRUE
# todo: make knock pin software-selectable?
# todo: DDEFS += -DEFI_SOFTWARE_KNOCK=TRUE

#DDEFS += -DEFI_SOFTWARE_KNOCK=TRUE -DSTM32_ADC_USE_ADC3=TRUE
#DDEFS += -DEFI_ENGINE_CONTROL = FALSE
DDEFS += -DEFI_BOOST_CONTROL = FALSE
#DDEFS += -DEFI_LAUNCH_CONTROL = FALSE
#DDEFS += -DEFI_ANTILAG_SYSTEM = FALSE
#DDEFS += -DEFI_DYNO_VIEW = FALSE
#DDEFS += -DEFI_TOOTH_LOGGER = FALSE
#DDEFS += -DEFI_HPFP = FALSE
#DDEFS += -DEFI_HD_ACR = FALSE
#DDEFS += -DEFI_RTC = FALSE
DDEFS += -DEFI_ALTERNATOR_CONTROL = FALSE
DDEFS += -DEFI_VVT_PID = FALSE
#DDEFS += -DEFI_SHAFT_POSITION_INPUT = FALSE
#DDEFS += -DEFI_IDLE_CONTROL = FALSE
#DDEFS += -DEFI_IDLE_PID_CIC = FALSE
#DDEFS += -DEFI_ENGINE_EMULATOR = FALSE
#DDEFS += -DEFI_ENGINE_SNIFFER = FALSE
#DDEFS += -DEFI_ELECTRONIC_THROTTLE_BODY = FALSE
#DDEFS += -DEFI_MALFUNCTION_INDICATOR = FALSE
